-- MySQL Script generated by MySQL Workbench
-- 10/21/17 21:38:35
-- Model: Online Store Schema    Version: 3.5

-- Model online store schema for use in COMP344, "E-Commerce Technologies"

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product` ;

CREATE TABLE IF NOT EXISTS `Product` (
  `prod_id` INT NOT NULL AUTO_INCREMENT,
  `prod_name` VARCHAR(40) NOT NULL,
  `prod_desc` VARCHAR(128) NULL DEFAULT NULL,
  `prod_img_url` VARCHAR(128) NULL DEFAULT NULL,
  `prod_long_desc` VARCHAR(256) NULL DEFAULT NULL,
  `prod_sku` CHAR(16) NULL DEFAULT NULL,
  `prod_disp_cmd` VARCHAR(128) NULL DEFAULT NULL,
  `prod_weight` DECIMAL(6,2) NULL,
  `prod_l` INT NULL,
  `prod_w` INT NULL,
  `prod_h` INT NULL,
  PRIMARY KEY (`prod_id`),
  INDEX `prod_name` (`prod_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1
COMMENT = 'Key product information.';


-- -----------------------------------------------------
-- Table `Attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Attribute` ;

CREATE TABLE IF NOT EXISTS `Attribute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `Product_prod_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Attribute_Product1_idx` (`Product_prod_id` ASC),
  CONSTRAINT `fk_product_id`
    FOREIGN KEY (`Product_prod_id`)
    REFERENCES `Product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1
COMMENT = 'Product attribute name and type information';


-- -----------------------------------------------------
-- Table `AttributeValue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttributeValue` ;

CREATE TABLE IF NOT EXISTS `AttributeValue` (
  `AttrVal_id` INT NOT NULL AUTO_INCREMENT,
  `AttrVal_Value` VARCHAR(45) NOT NULL,
  `AttrVal_Attr_id` INT NOT NULL,
  `AttrVal_Prod_id` INT NOT NULL,
  `AttrVal_Price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`AttrVal_id`),
  UNIQUE INDEX `id_UNIQUE` (`AttrVal_id` ASC),
  INDEX `fk_AttributeValue_Attribute_idx` (`AttrVal_Attr_id` ASC),
  INDEX `fk_Prod_id_idx` (`AttrVal_Prod_id` ASC),
  CONSTRAINT `fk_Attr_Id`
    FOREIGN KEY (`AttrVal_Attr_id`)
    REFERENCES `Attribute` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prod_id`
    FOREIGN KEY (`AttrVal_Prod_id`)
    REFERENCES `Product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Product attribute value information.';


-- -----------------------------------------------------
-- Table `ShopperGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShopperGroup` ;

CREATE TABLE IF NOT EXISTS `ShopperGroup` (
  `ShopGrp_id` INT NOT NULL,
  `ShopGrp_Name` VARCHAR(45) NOT NULL,
  `ShopGrp_Description` VARCHAR(256) NULL,
  PRIMARY KEY (`ShopGrp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shopper` ;

CREATE TABLE IF NOT EXISTS `Shopper` (
  `shopper_id` INT NOT NULL AUTO_INCREMENT,
  `sh_username` VARCHAR(30) NOT NULL,
  `sh_password` CHAR(60) NOT NULL,
  `sh_email` VARCHAR(64) NOT NULL,
  `sh_phone` VARCHAR(45) NULL DEFAULT NULL,
  `sh_type` CHAR(1) NOT NULL,
  `sh_shopgrp` INT NOT NULL,
  `sh_field1` VARCHAR(128) NULL DEFAULT NULL,
  `sh_field2` VARCHAR(128) NULL DEFAULT NULL,
  `sh_primaryAddressFK` INT NOT NULL,
  PRIMARY KEY (`shopper_id`),
  INDEX `sh_username` (`sh_username` ASC),
  INDEX `fk_Shopper_ShopperGroup1_idx` (`sh_shopgrp` ASC),
  CONSTRAINT `fk_Shopper_ShopperGroup1`
    FOREIGN KEY (`sh_shopgrp`)
    REFERENCES `ShopperGroup` (`ShopGrp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1
COMMENT = 'Information about a registered shopper and or user.';


-- -----------------------------------------------------
-- Table `Shaddr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shaddr` ;

CREATE TABLE IF NOT EXISTS `Shaddr` (
  `shaddr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `shopper_id` INT NOT NULL,
  `sh_title` CHAR(8) NULL DEFAULT NULL,
  `sh_firstname` VARCHAR(20) NULL DEFAULT NULL,
  `sh_familyname` VARCHAR(30) NULL DEFAULT NULL,
  `sh_street1` VARCHAR(64) NULL DEFAULT NULL,
  `sh_street2` VARCHAR(64) NULL DEFAULT NULL,
  `sh_city` VARCHAR(32) NULL DEFAULT NULL,
  `sh_state` VARCHAR(8) NULL DEFAULT NULL,
  `sh_postcode` VARCHAR(10) NULL DEFAULT NULL,
  `sh_country` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`shaddr_id`),
  INDEX `shopper_id` (`shopper_id` ASC),
  CONSTRAINT `fk_shopper_id`
    FOREIGN KEY (`shopper_id`)
    REFERENCES `Shopper` (`shopper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1
COMMENT = 'A shopper can have multiple shipping or other addresses.';


-- -----------------------------------------------------
-- Table `Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Order` ;

CREATE TABLE IF NOT EXISTS `Order` (
  `Order_id` INT NOT NULL AUTO_INCREMENT,
  `Order_Shopper` INT NOT NULL,
  `Order_Shaddr` INT NOT NULL,
  `Order_TimeStamp` TIMESTAMP NULL,
  `Order_PayMethod` CHAR NULL,
  `Order_Payment_PAN` VARCHAR(20) NULL,
  `Order_PAN_Exp_Month` SMALLINT NULL,
  `Order_PAN_Exp_Year` SMALLINT NULL,
  `Order_PaymentAuthorized` TINYINT(1) NULL,
  `Order_Picked` TINYINT(1) NULL,
  `Order_Shipped` TINYINT(1) NULL,
  `Order_ShipDate` DATE NULL,
  `Order_Paid` TINYINT(1) NULL,
  `Order_PayDate` DATE NULL,
  `Order_ShippingAmount` DECIMAL(10,2) NULL,
  `Order_TaxAmount` DECIMAL(10,2) NULL,
  `Order_ProductAmount` DECIMAL(10,2) NULL,
  `Order_Total` DECIMAL(10,2) NULL,
  PRIMARY KEY (`Order_id`),
  INDEX `fk_Shopper_idx` (`Order_Shopper` ASC),
  INDEX `fk_Order_Shaddr_idx` (`Order_Shaddr` ASC),
  CONSTRAINT `fk_Shopper`
    FOREIGN KEY (`Order_Shopper`)
    REFERENCES `Shopper` (`shopper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Shaddr`
    FOREIGN KEY (`Order_Shaddr`)
    REFERENCES `Shaddr` (`shaddr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrderProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrderProduct` ;

CREATE TABLE IF NOT EXISTS `OrderProduct` (
  `OP_id` INT NOT NULL AUTO_INCREMENT,
  `OP_Order_id` INT NOT NULL,
  `OP_prod_id` INT NOT NULL,
  `OP_qty` INT NULL,
  PRIMARY KEY (`OP_id`),
  INDEX `fk_Order_has_Product_Product1_idx` (`OP_prod_id` ASC),
  INDEX `fk_OrderProduct_Order1_idx` (`OP_Order_id` ASC),
  CONSTRAINT `fk_OP_Product`
    FOREIGN KEY (`OP_prod_id`)
    REFERENCES `Product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderProduct_Order1`
    FOREIGN KEY (`OP_Order_id`)
    REFERENCES `Order` (`Order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrderProductAttributeValues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrderProductAttributeValues` ;

CREATE TABLE IF NOT EXISTS `OrderProductAttributeValues` (
  `OPAttr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `OPAttr_op_id` INT NOT NULL,
  `OPAttr_Attr_id` INT NOT NULL,
  `OPAttr_AttrVal_id` INT NOT NULL,
  PRIMARY KEY (`OPAttr_id`, `OPAttr_op_id`),
  INDEX `fk_Order_has_Product_has_AttributeValue_AttributeValue1_idx` (`OPAttr_AttrVal_id` ASC),
  INDEX `fk_Order_has_Product_has_AttributeValue_Order_has_Product1_idx` (`OPAttr_op_id` ASC),
  CONSTRAINT `fk_Order_has_Product_has_AttributeValue_Order_has_Product1`
    FOREIGN KEY (`OPAttr_op_id`)
    REFERENCES `OrderProduct` (`OP_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Product_has_AttributeValue_AttributeValue1`
    FOREIGN KEY (`OPAttr_AttrVal_id`)
    REFERENCES `AttributeValue` (`AttrVal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderProductAttributeValues_Attribute1`
    FOREIGN KEY (`OPAttr_op_id`)
    REFERENCES `Attribute` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Session` ;

CREATE TABLE IF NOT EXISTS `Session` (
  `id` CHAR(32) NOT NULL,
  `Shopper_id` INT NULL,
  `data` MEDIUMBLOB NULL,
  `time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_t` (`time` ASC),
  CONSTRAINT `fk_sess_shopper_id`
    FOREIGN KEY (`Shopper_id`)
    REFERENCES `Shopper` (`shopper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock` ;

CREATE TABLE IF NOT EXISTS `Stock` (
  `id` INT NOT NULL,
  `Stock_Prod_id` INT NULL,
  `Stock_Prod_AttrValue_id` INT NULL,
  `Stock_Qty` INT NULL,
  `Stock_SKU` VARCHAR(60) NULL,
  `Stock_Location` VARCHAR(60) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stock_Prod_id_idx` (`Stock_Prod_id` ASC),
  INDEX `fk_Stock_ProdAttrValue_id_idx` (`Stock_Prod_AttrValue_id` ASC),
  CONSTRAINT `fk_Stock_Prod_id`
    FOREIGN KEY (`Stock_Prod_id`)
    REFERENCES `Product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_ProdAttrValue_id`
    FOREIGN KEY (`Stock_Prod_AttrValue_id`)
    REFERENCES `AttributeValue` (`AttrVal_Prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdPrices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProdPrices` ;

CREATE TABLE IF NOT EXISTS `ProdPrices` (
  `PrPr_id` INT NOT NULL AUTO_INCREMENT,
  `PrPr_Prod_id` INT NOT NULL,
  `PrPr_ShopGrp` INT NOT NULL,
  `PrPr_Price` DECIMAL(10,2) NULL,
  INDEX `fk_ProdPrices_Product1_idx` (`PrPr_Prod_id` ASC),
  PRIMARY KEY (`PrPr_id`),
  INDEX `fk_Prod_ShGrp` (`PrPr_Prod_id` ASC, `PrPr_ShopGrp` ASC),
  INDEX `PrPr_ShopGrp_idx` (`PrPr_ShopGrp` ASC),
  CONSTRAINT `fk_ProdPrices_Product1`
    FOREIGN KEY (`PrPr_Prod_id`)
    REFERENCES `Product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PrPr_ShopGrp`
    FOREIGN KEY (`PrPr_ShopGrp`)
    REFERENCES `ShopperGroup` (`ShopGrp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Specials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Specials` ;

CREATE TABLE IF NOT EXISTS `Specials` (
  `id` INT NOT NULL,
  `Special_Product_id` INT NOT NULL,
  `Special_ProdAttrVal` INT NULL,
  `Special_ProdPrices_id` INT NULL,
  `Special_Start_Date` DATE NOT NULL,
  `Special_End_Date` DATE NOT NULL,
  `Special_Comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Specials_Prod_id_idx` (`Special_Product_id` ASC),
  INDEX `fk_Specials_ProdAttrVal_id_idx` (`Special_ProdAttrVal` ASC),
  INDEX `fk_Specials_ProdPrices1_idx` (`Special_ProdPrices_id` ASC),
  CONSTRAINT `fk_Specials_Prod_id`
    FOREIGN KEY (`Special_Product_id`)
    REFERENCES `Product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specials_ProdAttrVal_id`
    FOREIGN KEY (`Special_ProdAttrVal`)
    REFERENCES `AttributeValue` (`AttrVal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specials_ProdPrices1`
    FOREIGN KEY (`Special_ProdPrices_id`)
    REFERENCES `ProdPrices` (`PrPr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
